#!/bin/sh

set -e
TEMPFILE=$(mktemp -p "")
echo $TEMPFILE
trap "rm -rf $TEMPFILE" HUP INT QUIT TERM STOP PWR EXIT

# test if error in editor will be propagated
VISUAL=false sensible-editor "$TEMPFILE" || exit 0
exit 1
